project1/app1/urls.py
from django.conf import settings
from django.urls import path
from . import views
app_name="app1"

urlpatterns=[
  path("",views.index , name="index"),
  path('general/', views.general, name='general'),
  path('discussions/', views.discussions, name='discussions'),
  path("comment/post/<uuid:id>",views.comment_post , name="comment_post"),
  path("search",views.search , name="search"),
  path("comment/like/add/<uuid:id>",views.comment_like_add , name="comment_like_add"),
  path("comment/dislike/add/<uuid:id>",views.comment_dislike_add , name="comment_dislike_add"),
  path("like/add/<uuid:id>",views.like_add , name="like_add"),
  path("dislike/add/<uuid:id>",views.dislike_add , name="dislike_add"),
  path("user_resistration/",views.user_resistration , name="user_resistration"),
  path("discussions/ranking/",views.ranking , name="ranking"),
  path("calculate/score",views.caluculate_score , name="caluculate_score"),
  path("create_guide_book/<int:id>",views.create_guide_book, name="create_guide_book"),
  path("search/guide",views.search_guide , name="search_guide"),
  path("general/detail/<str:tag>",views.guidebookdetail,name="guidebookdetail"),
]

project1/app1/models.py
from django.db import models
import uuid

# Create your models here.

class  Article(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    title=models.TextField(verbose_name="title")
    country=models.TextField(verbose_name="country")
    user_name=models.TextField(default="ゲスト",verbose_name="user_name")
    body=models.TextField(verbose_name="content")
    tag=models.ManyToManyField('Tags',verbose_name="tag",null=False,blank=False)
    picture=models.ImageField(upload_to="app1/picture/",null=True,blank=True,verbose_name="picture")
    created=models.DateTimeField(auto_now_add=True,verbose_name="created_date_time")
    edited=models.DateTimeField(auto_now_add=True,verbose_name="edited_date_time")
    likes=models.IntegerField(default=0,verbose_name="likes_count")
    dislikes=models.IntegerField(default=0,verbose_name="dislikes_count")
    comments=models.IntegerField(default=0,verbose_name="comments_count")
    score=models.IntegerField(default=0,verbose_name="score")

    def __str__(self):
        return self.title
    
class Tags(models.Model):
    name=models.CharField(max_length=43,unique=True)
    
    def __str__(self):
        return self.name


class Comment(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    article_id=models.ForeignKey(Article,verbose_name="ArticleID",on_delete=models.CASCADE)
    user_name=models.TextField(default="ゲスト",verbose_name="user_name")
    body=models.TextField(verbose_name="comment")
    created=models.DateTimeField(auto_now_add=True,verbose_name="created_date_time")
    likes=models.IntegerField(default=0,verbose_name="likes_count")
    dislikes=models.IntegerField(default=0,verbose_name="dislikes_count")

    def __str__(self):
        return self.body

class UserName(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    user_name=models.CharField(max_length=50,verbose_name="ユーザ名")
    password=models.CharField(max_length=50,null=True,blank=True,verbose_name="パスワード")
    score=models.IntegerField(default=0,verbose_name="スコア")
    def __str__(self):
        return self.user_name

class GuideBook(models.Model):
    id=models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    title=models.TextField(verbose_name="タイトル")
    body=models.TextField(verbose_name="本文")
    tag=models.ManyToManyField('Tags',verbose_name="tag",blank=True)
    created=models.DateTimeField(null=True,auto_now_add=True,verbose_name="作成時間")
    articles=models.IntegerField(null=True,verbose_name="参照した投稿の数")
    picture=models.ImageField(upload_to="app1/picture/",null=True,blank=True,verbose_name="picture")
    summary=models.TextField(null=True,verbose_name="要約")

    def __str__(self):
        return self.title

project1/app1/views.py
from datetime import timedelta, timezone
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from .forms import ArticleModelForm,CommentForm,UserRegistrationForm
from .models import Article,Comment,Tags,UserName,GuideBook
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from google import genai
cliant=genai.Client(api_key="AIzaSyCprYIJp44VWLGc-DK3pZigDmYapOAucDE")
#apiキーはこのアプリ以外で使用しないでください
#commentcomment


def create_summary(id):
    #反応が上位10件の投稿を抽出する
    articles = Article.objects.filter(tag__id=id).order_by('-score')
    tag_name=str(Tags.objects.get(id=id))
    #プロンプトを決める
    prompt="""
    以下の投稿とコメントを制約条件に基づいて要約してください。
    制約条件
    ・「分かりました」などの返事はせず、要約の文章のみを答えてください。
    ・要約はガイドブックの文章風に作成して、一つの文章にまとめてください。
    ・文章には何かの問題を解決する方法を必ず入れてください。
    ・全体が"""+tag_name+"""に一切関係ない投稿や、明らかに嘘の投稿は無視してください。
    ・「質問に対する返答または情報の補足」以外のコメントは無視してください。
    ・ユーザ名は無視してください。
    ・太文字や改行は使わずに、文字のみを使ってください。
    ・項目を大きく３つ程度に分けて段落分けしてください。
    ・文字数は1000文字を超えないようにしてください。
    """

    prompt_article=""
    article_count=1
    minimum_score=0
    for article in articles:
        if article.score>=minimum_score:
            prompt_article=prompt_article+"\n投稿"+str(article_count)+" (ユーザ名："+str(article.user_name)+")"+"\n"
            prompt_article=prompt_article+str(article.body)+"\n"
            comments = Comment.objects.filter(article_id=article).order_by('created')
            if len(comments)!=0:
                prompt_article=prompt_article+"投稿"+str(article_count)+"に対するコメント\n"
                for comment in comments:
                    prompt_article=prompt_article+"・"+str(comment.body)+"\n"
            article_count=article_count+1
    prompt=prompt+prompt_article
    print("プロンプト："+prompt)
    response=cliant.models.generate_content(model="gemini-2.5-flash-lite",contents=prompt)
    response=str(response.text)
    #print("レスポンス："+response)
    guidebook = GuideBook.objects.get(tag__name=tag_name)
    guidebook.body=response+"\n\n<元となった投稿>\n"+prompt_article
    guidebook.save()
    return response


class IndexView(View):
    def get(self,request):
        form=ArticleModelForm()
        tag_id=request.GET.getlist('tag')
        keyword=request.GET.get('q')
        articles=Article.objects.all()
        if tag_id:
            for tid in tag_id:
                articles = articles.filter(tag__id=tid)
            articles=articles.distinct()
        if keyword:
            articles=articles.filter(Q(title__icontains=keyword) | Q(body__icontains=keyword))
        comments=Comment.objects.all()
        tags=Tags.objects.all()
        return render(request,"app1/index.html",{"form":form,"articles":articles,"comments":comments,"tags":tags,"selected_tags":tag_id,"keyword":keyword})
    
class GeneralView(View):
    def get(self, request):
        # Logic for FAQ page
        tags = Tags.objects.all()
        tag_id = request.GET.getlist('tag')
        keyword = request.GET.get('q')
        guidebooks = GuideBook.objects.all()
        
        if tag_id:
            for tid in tag_id:
                guidebooks = guidebooks.filter(tag__id=tid)
            guidebooks = guidebooks.distinct()
        
        if keyword:
            guidebooks = guidebooks.filter(Q(title__icontains=keyword) | Q(body__icontains=keyword))
        context = {
            'tags': tags,
            'guidebooks' :guidebooks
        }
        return render(request, 'app1/general.html', context)

class DiscussionsView(View):
    def get(self, request):
        # Logic for discussions
        form = ArticleModelForm()
        tag_id = request.GET.getlist('tag')
        keyword = request.GET.get('q')
        articles = Article.objects.all().order_by("-created")
        
        if tag_id:
            for tid in tag_id:
                articles = articles.filter(tag__id=tid)
            articles = articles.distinct()
        
        if keyword:
            articles = articles.filter(Q(title__icontains=keyword) | Q(body__icontains=keyword))
        
        for article in articles:
            try:
                if article.user_name != "ゲスト":
                    user_obj = UserName.objects.get(user_name=article.user_name)
                    score = user_obj.score
                    if score < 5:
                        article.rank1_user = True
                    elif 5 <= score < 15:
                        article.rank2_user = True
                    elif 15 <= score < 100:
                        article.rank3_user = True
                    elif 100 <= score < 500:
                        article.rank4_user = True
                    elif 500 <= score < 2000:
                        article.rank5_user = True
                    elif 2000 <= score < 5000:
                        article.rank6_user = True
                    elif 5000 <= score < 10000:
                        article.rank7_user = True
                    elif 10000 <= score < 30000:
                        article.rank8_user = True
                    elif 30000 <= score < 100000:
                        article.rank9_user = True
                    elif score >= 100000:
                        article.rank10_user = True
                    else:
                        article.rank1_user = True
                else:
                    article.is_new_user = False
            except UserName.DoesNotExist:
                article.is_new_user = False
        
        comments = Comment.objects.all()
        tags = Tags.objects.all()
        
        context = {
            'form': form,
            'articles': articles,
            'comments': comments,
            'tags': tags,
            'selected_tags': tag_id,
            'keyword': keyword
        }
        return render(request, 'app1/discussions.html', context)
    
    def post(self, request):
        # Logic post same as IndexView
        form = ArticleModelForm(request.POST, request.FILES)
        if form.is_valid():
            form_body = form.cleaned_data.get('body')
            form.save()
            print("投稿を保存しました")
            article = Article.objects.get(body=form_body)
            #print("タグ一覧："+str(article.tag.all()))
            if article.tag.all():
                for tag in article.tag.all():
                    #print("タグ："+str(tag.id))
                    create_summary(int(tag.id))
            user = str(request.user)
            print("user:" + user)
            if user == "AnonymousUser":
                article.user_name = "ゲスト"
            else:
                article.user_name = str(user)
            article.save()
        else:
            print("投稿を保存できませんでした")
        
        return redirect('app1:discussions')

class CommentView(View):
    def get(self,request,id):
        article = get_object_or_404(Article, id=id)
        form = CommentForm()
        # Load post's comment
        comments = Comment.objects.filter(article_id=article).order_by('created')
        return render(request, "app1/comment_post.html", {
            "form": form,
            "article": article,
            "comments": comments,
        })
    def post(self,request,id):
        form = CommentForm(request.POST)
        article = get_object_or_404(Article, id=id)
        if form.is_valid():
            form_body = form.cleaned_data.get('body')
            comment = Comment()
            comment.article_id = article
            comment.body = str(form_body)
            user = str(request.user)
            if user=="AnonymousUser":
                comment.user_name="ゲスト"
            else:
                comment.user_name=str(user)
            comment.save()

            article.comments = article.comments + 1
            article.save()
            # After add comment, reload post's comment
            comments = Comment.objects.filter(article_id=article).order_by('created')
            form = CommentForm()
            return render(request, "app1/comment_post.html", {
                "form": form,
                "article": article,
                "comments": comments,
            })
        comments = Comment.objects.filter(article_id=article).order_by('created')
        return render(request, "app1/comment_post.html", {
            "form": form,
            "article": article,
            "comments": comments,
        })

class SearchView(View):
    def get(self,request):
        tag_id=request.GET.get('tag')
        keyword=request.GET.get('q')
        if tag_id=='1':
            return redirect("app1:discussions")
        params=request.GET.copy()
        if tag_id:
            if not tag_id in request.GET.getlist('tag'):
                params.appendlist('tag',tag_id)
        if keyword:
            params['q']=keyword
        return redirect(f"/discussions/?{params.urlencode()}")
    
class SearchGuidebookView(View):
    def get(self,request):
        tag_id=request.GET.get('tag')
        keyword=request.GET.get('q')
        if tag_id=='1':
            return redirect("app1:discussions")
        params=request.GET.copy()
        if tag_id:
            if not tag_id in request.GET.getlist('tag'):
                params.appendlist('tag',tag_id)
        if keyword:
            params['q']=keyword
        return redirect(f"/general/?{params.urlencode()}")


class LikeView(View):
    def get(self,request,id):
        article=get_object_or_404(Article,id=id)
        article.likes=article.likes+1
        article.score=article.likes-article.dislikes*2
        article.save()

        if article.user_name != "ゲスト":
            user=get_object_or_404(UserName,user_name=article.user_name)
            user.score=user.score+1
            user.save()
        
        next_url = request.GET.get('next')
        if next_url:
            return redirect(next_url)
        return redirect("app1:discussions")


class DislikeView(View):
    def get(self,request,id):
        article=get_object_or_404(Article,id=id)

project1/templates/app1/general.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>海外セカンドガイド - ガイドブック</title>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;600;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <!--  CSS file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'app1/css/style.css' %}">
</head>
<body>

    <!-- Header & navbar -->
    <header class="navbar">
        <div class="navbar-brand">セカンドガイド</div>
        <nav class="navbar-menu">
            <a href="{% url 'app1:index' %}" class="nav-item" style="text-decoration: none;">ホーム</a>
            <a href="{% url 'app1:general' %}" class="nav-item active" style="text-decoration: none;">セカンドガイドブック</a>
            <a href="{% url 'app1:discussions' %}" class="nav-item" style="text-decoration: none;">ディスカッション</a>
        </nav>
    
        {% if request.user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="post" style="margin: 0 0 0 auto; margin-right: 10px;"> 
            {% csrf_token %}
            <button type="submit" id="country-select" class="country-select" style="background-color: white;">{{request.user}}からログアウト</button>
        </form>
    
        {% else %}
        <button onclick="location.href='/login'" id="country-select" class="country-select" style="margin: 0 0 0 auto; margin-right: 10px; background-color: white;" >ログイン/新規登録</button>
        {% endif %}
        
        <div class="navbar-actions">
            <select id="country-select" class="country-select">
                <option value="ベトナム">ベトナム</option>
                <option value="all">全ての国</option>
                <option value="日本">日本</option>
                <option value="アメリカ">アメリカ</option>
                <option value="フランス">フランス</option>
            </select>
        </div>
    </header>

        

    <main class="container">
        <div class="page-content-wrapper">
            <div class="sidebar">
                <h3>タグ</h3>
                <div id="issue-tags" class="tag-list">
                    {% for tag in tags %}
                        {% if tag.id == 1 %}
                        <a href="/general" class="tag">{{ tag.name }}</a>
                        {% elif tag.id != 11 %}
                        <a href="{% url 'app1:search_guide' %}?tag={{ tag.id }}{% for t in selected_tags %}{% if t != tag.id|stringformat:'s' %}&tag={{ t }}{% endif %}{% endfor %}{% if keyword %}&q={{ keyword }}{% endif %}" class="tag">{{tag.name}}</a>
                        {% endif %}
                    {% endfor %}
                </div>
                <!-- Cập nhật phần search trong sidebar -->
    <div style="margin-top: 2rem;">
        <h3>キーワード検索</h3>
            <div class="search-box-container">
                <input type="text" id="general-search" placeholder="キーワードで検索..." class="form-input">
                <button type="button" id="general-search-button" class="btn-primary search-button">
                <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </div>
                
            <div class="content">
                <h1>セカンドガイドブック</h1>
                <div class="card-list">
                    {% for guidebook in guidebooks %}
                    {% if guidebook.title != "その他のガイドブック" %}

                    {% for tag in guidebook.tag.all %}
                     <a href="/general/detail/{{tag.name}}" style="text-decoration: none;">
                    {% endfor %}
                        <div class="card">
                        {% if guidebook.picture %}
                        <img src="{{guidebook.picture.url}}" alt="画像" class="card-image" style="background-color: #c1ffe0;">
                        {% else %}
                        <img src="" alt="画像" class="card-image" style="background-color: #c1ffe0;">
                        {% endif %}
                        <div class="card-content">
                            <h3 class="card-title">{{guidebook.title}}</h3>
                            <div class="card-description">
                                {{guidebook.body}}
                            </div>
                        </div>
                    </div>
                    </a>
                    {% endif %}
                    {% endfor %}

                    
                </div>
            </div>
        </div>
    </main>

    <script src="{% static 'app1/js/script.js' %}"></script>
</body>
</html>

project1/templates/app1/guidebookdetail.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>セカンドガイド - ガイドブック詳細</title>
    
    {% load static %}
    <link rel="stylesheet" href ="{% static 'app1/css/guidebook.css' %} ">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <button onclick="window.location.href='/general/'" class="back-button">
            <i class="fas fa-arrow-left"></i> 戻る
        </button>
        <h3 class="text-center">{{guidebook.title}}</h3>
        
        {% if guidebook.picture %}
            <div class="guidebook-image">
                <img src="{{ guidebook.picture.url }}" alt="{{ guidebook.title }}">
            </div>
        {% endif %}

        <p>{{guidebook.body|linebreaksbr}}</p>
    </div>
</body>
</html>

project1/templates/app1/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>セカンドガイド - ホーム</title>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;600;700;900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <!--  CSS file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'app1/css/style.css' %}">
</head>
<body>

    <!-- Header & navbar -->
    <header class="navbar">
        <div class="navbar-brand">セカンドガイド</div>
        <nav class="navbar-menu">
            <a href="{% url 'app1:index' %}" class="nav-item active" style="text-decoration: none;">ホーム</a>
            <a href="{% url 'app1:general' %}" class="nav-item" style="text-decoration: none;">セカンドガイドブック</a>
            <a href="{% url 'app1:discussions' %}" class="nav-item" style="text-decoration: none;">ディスカッション</a>
        </nav>
    
        {% if request.user.is_authenticated %}
        <form action="{% url 'accounts:logout' %}" method="post" style="margin: 0 0 0 auto; margin-right: 10px;"> 
            {% csrf_token %}
            <button type="submit" id="country-select" class="country-select" style="background-color: white;">{{request.user}}からログアウト</button>
        </form>
    
        {% else %}
        <button onclick="location.href='/login'" id="country-select" class="country-select" style="margin: 0 0 0 auto; margin-right: 10px; background-color: white;" >ログイン/新規登録</button>
        {% endif %}
        
        <div class="navbar-actions">
            <select id="country-select" class="country-select">
                <option value="ベトナム">ベトナム</option>
                <option value="all">全ての国</option>
                <option value="日本">日本</option>
                <option value="アメリカ">アメリカ</option>
                <option value="フランス">フランス</option>
            </select>
        </div>
    </header>

    <main class="container">
        <!-- home page -->
        <div class="slideshow-container">
            <img class="slideshow-image active" src="https://abvietnamtravel.com/img/logo/75B82SV64B_408255330_739691568182256_1104935954509976190_n.jpg" alt="ベトナムの美しい風景">
            <img class="slideshow-image" src="https://wallpapercat.com/w/full/7/b/f/717538-1920x1080-desktop-1080p-tokyo-japan-background-photo.jpg" alt="日本の桜と文化">
            <img class="slideshow-image" src="https://tranbathoaimdphd.wordpress.com/wp-content/uploads/2018/12/1-new-york_1.jpg" alt="ニューヨークの街並み">
            <img class="slideshow-image" src="https://images.unsplash.com/photo-1471623432079-b009d30b6729?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="フランスの美しい景色">
            <img class="slideshow-image" src="https://images.unsplash.com/photo-1486299267070-83823f5448dd?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="england">
        </div>
        <div class="welcome-message">
            <h2>ベトナム在住に関する課題を共有しよう</h2>
            <p>このアプリでは、既存のガイドブックには掲載されていない有益な情報を交換できます。<br>
            <p>よりよい情報を提供し、上位ランクを目指しましょう。</p>
            <a href="{% url 'app1:discussions' %}" class="cta-button">ディスカッションに参加する</a>
        </div>
    </main>

    <script src="{% static 'app1/js/script.js' %}"></script>
</body>
</html>

project1/templates/app1/user_registration.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app1/css/register_style.css' %}">
    <title>Document</title>
</head>
<body class="bg-gray-100">
    <div class="registration-container">

        <div>
            <div>
            {% block content %}
            {% endblock %}
            </div>
        </div>
<h2>新規登録</h2>
    <form method="post">
    {% csrf_token %}
    <div class = form-group>
    <label for="id_user_name" class = "form-label">ユーザ名:</label>
    <input type="text" name="user_name" maxlength="50" required="" id="id_user_name" class="form-input" placeholder="ユーザ名">
    </div>
    <div class = form-group>
    <label for="id_password" class="form-label">パスワード:</label>
    <input type="password" name="password" maxlength="50" id="id_password" class = "form-input" placeholder="パスワード">
    </div>
    <!-- チェックを付けないと押せないように修正する -->
        
    <!-- {{ form.as_p }} -->
    <button type="submit" class="submit-btn">登録</button>
    </form>
        <div class="form-link"></div>
            <br>
                <a href="/login" class = "login-link">ログイン</a>
            <br>
                <a href="/" class = "registration-link">ゲストとして続行</a>
        </div>
    </div>
</body>